apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fcg-games-ingress
  namespace: fcg
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/games
            pathType: Prefix
            backend:
              service:
                name: fcg-games-svc
                port:
                  number: 80
